# Generated by Django 4.1.3 on 2022-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internet_seesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('usage_time', models.DateTimeField(verbose_name='usage time')),
                ('ip', models.CharField(max_length=255, verbose_name='ip')),
                ('MAC', models.CharField(max_length=255, verbose_name='MAC')),
                ('upload', models.BooleanField(verbose_name='upload')),
                ('download', models.BooleanField(verbose_name='download')),
                ('total_transfers', models.BooleanField(verbose_name='total transfers')),
                ('session_break_reason', models.CharField(max_length=255, verbose_name='session break reason')),
            ],
        ),
    ]
