# Generated by Django 4.1.3 on 2022-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetsession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_seesion',
            name='start_time',
            field=models.CharField(max_length=255, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='internet_seesion',
            name='usage_time',
            field=models.CharField(max_length=255, verbose_name='usage time'),
        ),
    ]
