# Generated by Django 4.1.3 on 2022-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetsession', '0002_alter_internet_seesion_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_seesion',
            name='download',
            field=models.FloatField(verbose_name='download'),
        ),
        migrations.AlterField(
            model_name='internet_seesion',
            name='total_transfers',
            field=models.FloatField(verbose_name='total transfers'),
        ),
        migrations.AlterField(
            model_name='internet_seesion',
            name='upload',
            field=models.FloatField(verbose_name='upload'),
        ),
    ]
